tsuji.rag.index-path=l10n/rag/index
tsuji.language.from=en
tsuji.language.to=ja

# Translator Configuration
tsuji.translator.type=deepl

# DeepL Configuration
# tsuji.translator.deepl.api-key=

tsuji.jekyll.cname=
tsuji.jekyll.surge-domain-suffix=

quarkus.package.jar.type=uber-jar
quarkus.package.jar.add-runner-suffix=false

quarkus.langchain4j.ai.gemini.log-requests=true
quarkus.langchain4j.ai.gemini.log-responses=true
quarkus.langchain4j.ai.gemini.timeout=60s
